CREATE DATABASE IF NOT EXISTS logs;

USE logs;

CREATE TABLE IF NOT EXISTS log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    app VARCHAR(25) NOT NULL,
    type VARCHAR(50) NOT NULL,
    message VARCHAR(200),
    time DATETIME NOT NULL
)ENGINE=InnoDB;